# Generated by Django 5.2.13 on 2026-04-26 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='merchants.bankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('failed', 'Failed'), ('hung', 'Hung'), ('timeout', 'Timeout')], max_length=16, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payouts.payout')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutStateTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('actor', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='payouts.payout')),
            ],
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'locked_at'], name='payouts_pay_status_6eaed7_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'next_retry_at'], name='payouts_pay_status_0e8e83_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['merchant', '-created_at'], name='payouts_pay_merchan_e714be_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='payout_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payoutattempt',
            constraint=models.UniqueConstraint(fields=('payout', 'attempt_number'), name='uniq_payout_attempt'),
        ),
    ]
