# Generated by Django 5.2.13 on 2026-04-26 14:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('hold', 'Hold'), ('release', 'Release')], max_length=16)),
                ('amount_paise', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payouts.payout')),
            ],
            options={
                'indexes': [models.Index(fields=['merchant', 'created_at'], name='ledger_ledg_merchan_36e37b_idx'), models.Index(fields=['payout'], name='ledger_ledg_payout__f9815b_idx'), models.Index(fields=['merchant', 'entry_type'], name='ledger_ledg_merchan_13a18a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paise__gt', 0)), name='ledger_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'credit'), ('payout__isnull', True)), models.Q(('entry_type__in', ['hold', 'release']), ('payout__isnull', False)), _connector='OR'), name='ledger_payout_required_for_hold_release')],
            },
        ),
    ]
